### ISSUE TITLE
Fix Many Misspelled Territory Names

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-maps/napoleonic_empire#2]
Lots of names that aren't quite right for example 'Lombardi' -> 'Lombardy' and 'Eturia' -> 'Etruria'.

**Comment by ron-murhammer** [comment]
Here is the list of changes:
Orleanais->Ile-de-France 
Scandinavians->Fells
Lombardi->Lombardy
Eturia->Etruria
Norvege->Norway
Warszowa->Warsaw
Alemtejo->Alentejo
Kirghix->Kirghiz
Hanovre->Hanover

**Comment by ron-murhammer** [comment]
More:
Galacia->Galicia
Estremadura->Extremadura

**Comment by Cernelius** [comment]
In case anyone will refer to this issuew to upgrade or downgrade any maps or mods, I'm adding the critical info that, before making the aforementioned names changes, you need to change:

Galicia->Lodomeria

@ron-murhammer I suggest having the full list of names changes in the first post at this topic.

Side note, Lodomeria is only a different name for Volhynia, already on the map, and just fancifully claimed by Austria; so I think the best would have been "East Galicia", while renaming "Krakow" as "West Galicia".
I know I didn't want to help with renaming and said I would not have commented, but just saying so since this is a case of a territory that I believe got worse from before.
